### ISSUE TITLE
Where i shoud fill in my Username and Password

### ISSUE THREAD

**Issue by Cyber-sKO** [vHack-API/vHackAPI-Java#20]

**Comment by Qup42** [comment]
Have a look at the examples. They should be self-explanatory and give you a feeling about how the api works. (Hint you have to fill them in in Line 13)
@checkium will make a rewrite soon. We'll also along with it create a bot that you can use without any programming knowledge.

**Comment by itsfolf** [comment]
As stated in the examples you need to create your API instance using:
` vHackAPI api = new vHackAPIBuilder().password("pass").username("user").getAPI();`
You can get more info here: [Examples](https://github.com/vHack-API/vHackAPI-Java/tree/master/src/examples).
If you need further help you can join our discord: [![Discord](https://img.shields.io/badge/Chat-%20on%20Discord-738bd7.svg)](https://discord.gg/PHgESQn)
