### ISSUE TITLE
JSON Exception

### ISSUE THREAD

**Issue by Jason-Souma** [vHack-API/vHackAPI-Java#23]
`Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	at org.json.JSONObject.<init>(JSONObject.java:195)
	at org.json.JSONObject.<init>(JSONObject.java:319)
	at me.checkium.vhackapi.vHackAPI.getStats(vHackAPI.java:52)
	at me.checkium.vhackapi.vHackAPI.<init>(vHackAPI.java:81)
	at me.checkium.vhackapi.vHackAPIBuilder.getAPI(vHackAPIBuilder.java:55)
	at examples.ConsoleExample.main(ConsoleExample.java:11)
`
I"m new to java and coding in general and would like to know where I'm going wrong and what to do with regards to getting this compiled and working.

**Comment by itsfolf** [comment]
How can I reproduce the error?

**Comment by Jason-Souma** [comment]
What I did was I downloaded the source using git in Eclipse, launched the project, linked the json-20160810.jar library and ran the code as a java application looking to see if it would work straight away.

**Comment by itsfolf** [comment]
You need to compile the code into a jar, and import it into your own project.

**Comment by Jason-Souma** [comment]
What code would my own project have to get it to work?

**Comment by itsfolf** [comment]
look at examples class

**Comment by Qup42** [comment]
you can also stay with the examples but you'd then have to replace "password" and "user" with Your password and user name

**Comment by itsfolf** [comment]
yes

**Comment by Jason-Souma** [comment]
What would be the password as I don't recall having to input a password when I first signed up?

**Comment by itsfolf** [comment]
To register on vHack, you need to input email, password and username, if you dont remeber yours you need to contact vHack devs, we can't help you on that.

**Comment by Jason-Souma** [comment]
Okay thanks for the help

**Comment by Qup42** [comment]
@Jason-Souma i think that you can also send a password reset e mail from the login interface of the app but down pin me down on that

**Comment by Jason-Souma** [comment]
@Qup42 There is, thanks again.

**Comment by Jason-Souma** [comment]
Okay so I got it to work but I assume that I need to make the gui if I want one and it seems that only console example runs.

**Comment by Qup42** [comment]
yes if you want an gui you'd need to build it yourself. although they're old all examples(.java files) should work the ChatExample is more documentation than example but you can also have a look at it. also dont forget to replace the credentials with your own
