### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Jason-Souma** [vHack-API/vHackAPI-Java#24]
Explanation:
During a run of the API, there are spontaneous NullPointerExceptions from the line:
`if(scanned.getSuccessRate() >= 70) {`
with error message:
`Exception in thread "main" java.lang.NullPointerException
	at examples.ConsoleExample.main(ConsoleExample.java:17)`

Recreation:
You can recreate this through running the API compiled straight from this git repo, could be on the first run or second or 100th run.

API Version:
https://api.vhack.cc/v/8/ - Believe I could say it's version 8 of the API?
Or if not that then V1.41.

**Comment by itsfolf** [comment]
It may be caused by too many requests at the same time, could you try adding some delay bewteen them?

**Comment by Jason-Souma** [comment]
I've currently got a 2 second delay between each run, but I did notice that when I tried a longer delay they occurred less often.

**Comment by Jason-Souma** [comment]
Tried it with a 3 second delay now and only occurred like 30 runs down the line.

**Comment by OrtiMussPrime** [comment]
I've been coding the last weeks as well and I've found out that it is connected to the delays, the best working one is a 4 second delay. I am going to push the code in a few days.

**Comment by Jason-Souma** [comment]
Okay, thanks. Are there any changes that have been mode?

**Comment by Jason-Souma** [comment]
*Made

**Comment by itsfolf** [comment]
Also, you should make your own code instead of running the examples. You should compile the API into a .jar and then use it in your build path.

**Comment by OrtiMussPrime** [comment]
Yes, I edited many parts of the Code and made already a money farming bot that works pretty stable

**Comment by Jason-Souma** [comment]
I have heavily changed the code already. 
This is what I'm currently working with:
`package examples;

//import java.util.ArrayList;
//import java.util.List;

import me.checkium.vhackapi.vHackAPI;
import me.checkium.vhackapi.vHackAPIBuilder;
import me.checkium.vhackapi.console.ScannedNode;
import me.checkium.vhackapi.console.TransferResult;
import java.util.Scanner;

public class ConsoleExample {
	public static void main(String[] args) throws InterruptedException {
		 vHackAPI api = new vHackAPIBuilder().password("teststudent").username("Dos3r123").getAPI();
		 String Loop;
		 Integer LoopCount = 1;
		 
		 Scanner in = new Scanner(System.in);
		    try{
		        System.out.println("Would You Like To Loop? (Yes/No)    :");
		        Loop = in.next();
		        if(Loop.equals("yes")) {
		        System.out.println("How Many Times Do You Want To Loop? :");
		        LoopCount = in.nextInt();
		        }
		        int i = 0 ;
				while( i < LoopCount ) {
					String ip = api.getConsole().getIP(false, false);
					ScannedNode scanned = api.getConsole().scanIP(ip);
					if(scanned.getSuccessRate() >= 70) {
						if(scanned.isAnonymous()) {
						     	//Prints out first lines
							 	System.out.println("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■");
							 	System.out.println("■ vHack XT        : Personal Edition        ■");
							 	System.out.println("■                                           ■");					 					 
							 	//Inserts ■ at 44th position to create a Box at Scan Report
							 	String ScanReport = "■ Scan Report For : " + scanned.getIP() + "                                    ";
							 	StringBuilder sb1 = new StringBuilder(ScanReport);
							 	sb1.setCharAt(44, '■');
							 	ScanReport = sb1.toString();
							 	System.out.println(ScanReport);
							 	System.out.println("■                                           ■");
							 	//Inserts ■ at 44th position to create a Box at Username
							 	String Username = "■ [+]Username     : " + scanned.getUsername() + "                                ";
							 	StringBuilder sb2 = new StringBuilder(Username);
							 	sb2.setCharAt(44, '■');
							 	Username = sb2.toString();
							 	System.out.println(Username);
							 	//Inserts ■ at 44th position to create a Box at Money
							 	String Money1 = Integer.toString(scanned.getMoney());
							 	Money1 = new StringBuilder(Money1).insert(Money1.length()-3, " ").toString();
							 	Money1 = new StringBuilder(Money1).insert(Money1.length()-7, " ").toString();
							 	String Money = "■ [+]Money        : $" + Money1 + "                                                 ";
							 	StringBuilder sb8 = new StringBuilder(Money);
							 	sb8.setCharAt(44, '■');
							 	Money = sb8.toString();
							 	System.out.println(Money);
							 	//Prints a line as a breaker
							 	System.out.println("■                                           ■");
							 	//After All Those Print Lines It Will Then Trojan Transfer As Seen Below
							 	//If It's Successful It Will Go To If Otherwise It Will Go To Else
							 	TransferResult transfer = api.getConsole().transferTrojanTo(scanned);
							 	if(transfer.getSuccess()){
							 		//Inserts ■ at 44th position to create a Box at MoneyGet
							 		String Money2 = Integer.toString(transfer.getMoneyAmount());
							 		Money2 = new StringBuilder(Money2).insert(Money2.length()-3, " ").toString();
							 		Money2 = new StringBuilder(Money2).insert(Money2.length()-7, " ").toString();
							 		String MoneyGet = "■ Money Gained : $" + Money2 + "                                             ";
							 		StringBuilder sb13 = new StringBuilder(MoneyGet);
							 		sb13.setCharAt(44, '■');
							 		MoneyGet = sb13.toString();
							 		System.out.println(MoneyGet);
							 		//Inserts ■ at 44th position to create a Box at RepGet
							 		String RepGet = "■ Rep Gained   : +" + transfer.getRepGained() + "                              ";
							 		StringBuilder sb14 = new StringBuilder(RepGet);
							 		sb14.setCharAt(44, '■');
							 		RepGet = sb14.toString();
							 		System.out.println(RepGet);
							 		//Prints final line
							 		System.out.println("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■");
							 	}else {
							 		System.out.println("■ Transfer Failed   :  True                 ■");
							 		//Inserts ■ at 44th position to create a Box at RepLost
							 		String RepLost = "■ Rep Lost          : -" + transfer.getRepLost() + "                          ";
							 		StringBuilder sb15 = new StringBuilder(RepLost);
							 		sb15.setCharAt(44, '■');
							 		RepLost = sb15.toString();
							 		System.out.println(RepLost);
							 		//Prints final line
							 		System.out.println("■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■");
							 		}
						}else {
							System.out.println("*********************************************");
							System.out.println("*          Failed! Was Not Anon             *");
							System.out.println("*********************************************");
							}
					}else {
						System.out.println("*********************************************");
						System.out.println("*       Failed! Success Rate Too Low        *");
						System.out.println("*********************************************");
						}
					Thread.sleep((long)(Math.random() * 1000));
					Thread.sleep((4000));
					i++;
			}
				System.out.println("Loop Done!");
		}finally {
			in.close();
		   	}
	}
}
		    
		 `

**Comment by itsfolf** [comment]
@OrtiMussPrime There's a big update coming, so changing the API is a bit of waste of time right now since the new version will be backwards incompatible.

**Comment by OrtiMussPrime** [comment]
There is a easier way, since they had implemented a "getIPs()" function. I worked with that and I hack 20 IPs in around 40 Seconds.

**Comment by Jason-Souma** [comment]
It's mainly aesthetic changes to mimic the GUI's of old cause I have not been able to learn how to build a GUI in Eclipse yet :\

**Comment by OrtiMussPrime** [comment]
@checkium Okey good to know. I want also write an Upgrade algorithm, maybe we could sit together and get something done, since my skills are advanced but not that neat

**Comment by OrtiMussPrime** [comment]
@Jason-Souma @checkium  Also I am looking to forward to develop a small and easy GUI for easier use

**Comment by Jason-Souma** [comment]
That would be great @OrtiMussPrime

**Comment by Jason-Souma** [comment]
Thanks for all your guys hard work on this ey.
