### ISSUE TITLE
Upload adware response

### ISSUE THREAD

**Issue by angelbirth** [vHack-API/vHackAPI-Java#3]
I have been tinkering with your code, but I got false positive every time I `uploadAdware` (returns false but actually uploaded). In the code it says "return true if the response contains 11"
My question, what is this "11"? Some kind of magic number?

**Comment by angelbirth** [comment]
never mind, it should be "0"

**Comment by itsfolf** [comment]
Did you compile The source or downloads from releases? If you download there may be an error because the Game updated yesterday, I fixed The code but didnt uploaded compiled jar yet.

**Comment by angelbirth** [comment]
I cloned from this repo. Anyway, it's fixed. As I said, it should be "0", not "11". Your edited code runs fine now. Thanks
