### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by rshacker13** [vHack-API/vHackAPI-Java#5]
How do you use this? Thanks in advance and sorry for the question.

**Comment by angelbirth** [comment]
Do you have basic java knowledge? If you do, see packages `example`. The program should explain it to you.

**Comment by itsfolf** [comment]
@rshacker13 can you answer to angelbirth question?

**Comment by rshacker13** [comment]
I see, thought that the jar file from the release would be a "stand-alone app"

**Comment by itsfolf** [comment]
@rshacker13 No, you need to import the jar file from releases into your build path. and use it. See the example code for how to use it.

**Comment by rshacker13** [comment]
I see, tyvm!
