### ISSUE TITLE
Check my upgrade level

### ISSUE THREAD

**Issue by angelbirth** [vHack-API/vHackAPI-Java#7]
Is there any way to see my current upgrade levels? (SDK, AV, fw, etc)
I want my bot to do automatic upgrades, and possibly raising the scanning threshold automatically (e.g. only attack nodes with av level < my sdk level)

**Comment by itsfolf** [comment]
yes, use api.getStats(Stats.av) for example.

**Comment by angelbirth** [comment]
Ah, I overlooked that. Thanks again! @checkium
