### ISSUE TITLE
Would like to understand the formation of 'pass' parameter on url

### ISSUE THREAD

**Issue by siqueira-ec** [vHack-API/vHackAPI-Java#8]
Can anyone explain me, step by step, **how the string 'pass' is formed**? I'm very noob in Java and i need some help.

Hope you understand my question, because my English is not the best.

Thank you in advance.

**Comment by itsfolf** [comment]
Why would you need to know that?

PS: Are you portuguese/brazilian?

**Comment by siqueira-ec** [comment]
I'm trying to port to other languages and integrate with other API i use.

PS: Yeah, i'm brazilian, haha

**Comment by itsfolf** [comment]
Yhea your surname "telled" me that.

1- You give it two strings "user::::pass" and "yourusername:::::yourpassword" replace your with your real password. Lets call the two strings str and str2.

```
String str = "user::::pass";
string str2 = "myuser::::mypass";
```

2- You split the two strings into two string[]'s called split and split2.

```
 String[] split = str.split("::::");
 String[] split2 = str2.split("::::");`
```

3- You set a string called str4 as "{" and loop trought split length putting in the json object the split and split2 with the key as value of the loop. And then put the current time in milis divided by 1000.

```
        long currentTimeMillis = System.currentTimeMillis() / 1000;
        String str4 = "{";
        JSONObject jSONObject = new JSONObject();
        for (int i = 0; i < split.length; i++) {
            try {
                jSONObject.put(split[i], split2[i]);
            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
        try {
            jSONObject.put("time", currentTimeMillis + "");
        } catch (JSONException e2) {
            e2.printStackTrace();
        }
```

4- You set the str4 as the json, and use the method encryptString() with the currentTimeinMillis divided by 1000 a empty string and str4.

```
str4 = jSONObject.toString();
 str4 = encryptString(currentTimeMillis + "" + str4);
```

5- You get some bytes and some strings. 

```
byte[] bytes3 = str5.getBytes();
 byte[] bytes4 = str4.getBytes();
str5 = generateUser(bytes3, 0, bytes3.length, byt, false);
 str4 = encryptString(encryptString(a2 + encryptString(encryptString(str5) + generateUser(bytes4, 0, bytes4.length, byt, false))));
```

6- Profit. str4 is your pass.

Btw, if you wanna I can add you to the language you want to port team and create a repository in the organization,

**Comment by siqueira-ec** [comment]
I thought you would explain to me as follows, haha:
1. take the user and concatenate with the encrypted (md5) N times password string...
2. concatenate with the current time in milliseconds...
3. and so on...

But thanks so much for the reply, I will study further the code as soon as possible and I want to port to JS/NodeJS.

PS: You can add me to the repository of JS/NodeJS, thanks.
PS2: Notice that I am with little time to devote to the project, so I apologize for any delay.

**Comment by siqueira-ec** [comment]
Can you explain me the method encryptString() ?

**Comment by itsfolf** [comment]
Later. The game updated and I'm working on fixing broken things.

**Comment by itsfolf** [comment]
@siqueira-ec 

1- Give it a string.

2- Get Message diggest with the instance "MD5"

```
 MessageDigest instance = MessageDigest.getInstance(md5s);
```

3- Set and get some bytes and create a stringbuilder

```
 instance.update(str.getBytes());
            byte[] digest = instance.digest();
            StringBuilder stringBuilder = new StringBuilder();
```

4- Make a loop on every byte of digest.

```
for (byte b : digest) {
                String toHexString = Integer.toHexString(b & 255);
                while (toHexString.length() < 2) {
                    toHexString = "0" + toHexString;
                }
                stringBuilder.append(toHexString);
            }
```

5- Return the strinb builder.

```
 return stringBuilder.toString();
```

**Comment by itsfolf** [comment]
@siqueira-ec Anything new can I close The issue?
