### ISSUE TITLE
invalid json respond

### ISSUE THREAD

**Issue by adeshinichi** [vHack-API/vHackAPI-Java#9]
i think the respond is changed again... tried sometimes and got same invalid error

**Comment by checkium** [comment]
Well, it's the same problem than before, they are using a untrusted certeficate. I just need to tell the API to trust it. I've removed that code because they changed the certeficate to a trusted one. Looks like they are back to the first (Let's Encrypt Authority x3).
Going to investigate.

**Comment by checkium** [comment]
Also, API 2.0 is a bit delayed since I'm busy with other projects. I think I'll just release a update for the current version.

**Comment by checkium** [comment]
Notes:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by checkium** [comment]
@adeshinichi I think it's fixed with new release. Can you test it?
